---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ga1
  template:
    metadata:
      labels:
        app: ga1
    spec:
      containers:
        - name: githubaction
          image: stdnoob/github-action-poc:latest
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: github-action-poc
spec:
  selector:
    app: g1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
