name: project cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      Key1: "This is temp env1"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: stdnoob/github-action-poc
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    env:
      Key1: "This is temp env2"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: azure/setup-minikube@v1
    - name: Try the cluster !
      run: kubectl get pods -A   
    - name: Deploy to minikube
      run: |
        minikube status
        kubectl apply -f minikube-deployment.yaml
    - name: Wait for service to become available
      run: |
        retries=0
        max_retries=5
        while [ $retries -lt $max_retries ]; do
          if kubectl get svc github-action-poc -o jsonpath='{.status.loadBalancer.ingress[0].ip}' | grep -qE '\d+\.\d+\.\d+\.\d+'; then
            break
          else
            retries=$((retries + 1))
            echo "Waiting for service to become available..."
            kubectl get pods
            kubectl get services
            kubectl get deployments
            kubectl get endpoints
            sleep 10
          fi
        done
    - name: Test service URLs
      run: |
          minikube status
          kubectl get pods
          kubectl get services
          kubectl get deployments
          kubectl get endpoints
          minikube service list
          minikube service github-action-poc --url
